feat : racing car
Java-Spring-Study/java-racing-car pull request #3
Opened 2022-11-11 13:09 UTC by llddang

2022-11-11 13:58 UTC, gusah009 requested changes
수고 많으셨습니다!

이건 [제 코드](https://github.com/JavaBlooming-In-Spring/java-challenges/tree/main/gusah009/java-racing-car/src/main/java/javablooming)입니다!

심심하실 때 구경하고 가세요~~!

2022-11-11 13:58 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/Main.java
> +    GamePlay gp = new GamePlay();
약어는 사용하지 않는게 좋습니다.

`gp`보다 `gamePlay`로 풀 네임을 적어주는게 더 가독성이 뛰어납니다.

2022-11-11 13:58 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/GamePlay.java
> +    carList = Arrays.stream(cars).map(car -> new Car(car)).collect(Collectors.toList());
`stream`을 작성할 때에는 한 줄에 하나씩 쓰시는 게 좋습니다.

가령 위의 코드는 아래와 같이 바꿀 수 있습니다.

```java
carList = Arrays.stream(cars)
                 .map(car -> new Car(car))
                 .collect(Collectors.toList());
```

2022-11-11 13:58 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/GamePlay.java
> +    while (!gv.isValidCarName(cars)) {
느낌표로 부정을 표현하기보다 함수명으로 `!isValidCarName` => `isInvalidCarName`이 좋습니다!

2022-11-11 13:58 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/GamePlay.java
> +  }
생성자에서 기본 필드들을 초기화 해주는 것은 좋은 것 같습니다!

2022-11-11 13:58 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/GamePlay.java
> +    return randomNumber > 3 ? true : false;
```java
return randomNumber > 3 ? true : false;
```
를
```java
return randomNumber > 3;
```
와 같이 바꿀 수 있을 것 같습니다!

2022-11-11 13:58 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/GamePlay.java
> +    final String[] winners = {""};
`String` 대신 `StringBuilder`를 사용해 보는것도 좋을 것 같습니다!

2022-11-11 13:58 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/util/GameValidator.java
> +  }
함수명이 `isValidTryCount`로 ` `tryCount`의 어떤 유효성을 검사하는 지 잘 모르겠습니다.

로직상으로 유추했을 때 `tryCount`가 숫자인지 확인하는 것 같은데, `Integer.parseInt`를 사용하면 더 간결하게 숫자인지 확인할 수 있을 것 같습니다!

2022-11-12 09:40 UTC, llddang commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/GamePlay.java
> +    return randomNumber > 3 ? true : false;
왘ㅋㅋㅋㅋㅋㅋ저 때 뭔 생각으로..ㅋㅋㅋ 부끄럽네요...

2022-11-12 14:51 UTC, woo-chang commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/domain/Car.java
> +    movement += "-";
`String`은 불변 객체라 해당 메서드가 생성될 때마다 매번 새로운 객체가 생성됩니다.

수정이 가능한 `StringBuilder`를 사용해보는 것도 좋을 것 같아요!

2022-11-12 14:51 UTC, woo-chang commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/util/GameValidator.java
> +     return Arrays.stream(cars).allMatch(car -> car.length() <= 5 && car.length() != 0);
```java
return Arrays.stream(cars).allMatch(this::validateCarNameLength);

public boolean validateCarNameLength(String car) {
    return car.length() <= 5 && car.length() != 0;
}
```
위와 같이 조건은 메서드로 분리하면 조건을 추상화하면서 의도를 더 명확하게 드러낼 수 있을 것 같습니다!

조금 더 추가하자면 `5`와 같은 값은 별도의 상수로 관리하는 방법이 좋습니다.

2022-11-12 14:51 UTC, woo-chang commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/GamePlay.java
> +      printCarState();
역할에 맞게 메서드로 분리하신 점 좋은 것 같습니다!

2022-11-12 14:51 UTC, woo-chang commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/GamePlay.java
> +    return random.nextInt() % 10;
```java
return random.nextInt(10);
```
위 코드가 동일한 결과를 반환하도록 할 수 있을 것 같아요!

2022-11-15 19:11 UTC, hyuunnn commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/util/GameValidator.java
> +  }
지금 코드는 이름의 길이가 5가 넘어가면 동작하네요.
저도 아직 모던하게 개발하는 것이 어색하지만, 아래 코드로 수정하면 정상적으로 동작합니다.
```java
  public boolean isInvalidCarName(String[] cars) {
    return Arrays.stream(cars).anyMatch(this::invalidateCarNameLength);
  }

  private boolean invalidateCarNameLength(String car){
    return car.length() > MAXLENGTH || car.length() == 0;
  }
```

2022-11-18 09:34 UTC, llddang commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/util/GameValidator.java
> +  }
앗.. 감사합니다!!

2022-11-18 11:09 UTC, gusah009 approved these changes
테스트코드도 작성해보시면 좋을 것 같습니다!!

수고 많으셨습니다!

앞으로 어떤 개발을 하실 지 모르지만 클린코드 책 추천드립니다!

2022-11-18 11:09 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/GamePlay.java
> +  }
`getCars` 와 `getTryCount` 메서드는 가져온다는 느낌이 강합니다.

필드에 해당 값들을 입력받아서 세팅하는 용도라면 `set`을 다는 건 어떠신가요?

2022-11-18 11:09 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/GamePlay.java
> +    }
`do while` 문으로 합치고, 에러메시지 출력은 유효성 체크 메서드 내부적으로 호출하는 것도 좋을 것 같습니다.

+) cars split을 매번 해줄 필요가 있을까요?

valid한 carNames가 들어왔을 때 split 해주면 더 효율적일 것 같습니다!

2022-11-18 11:09 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/GamePlay.java
> +      printCarState();
저도 좋은 것 같습니다!! 👍👍

2022-11-18 11:09 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/Main.java
> +    gamePlay.printWinner();
저는 각 매서드가 호출 순서에 영향을 받지 않아야 한다고 생각합니다!

제가 직접 돌려본건 아니지만 혹시 `startCarRacing` 없이 `printWinner`만 수행하면 어떻게 되나요??

2022-11-18 11:09 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/domain/Car.java
> +  private StringBuilder movement = new StringBuilder("");
`Car` 클래스 잘 만들어 사용하시는 것 같습니다!

2022-11-18 11:09 UTC, gusah009 commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/util/GameValidator.java
> +  }
메서드 참조 👍👍

2022-11-22 15:43 UTC, llddang commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/domain/Car.java
> +  private StringBuilder movement = new StringBuilder("");
감사합니다!

2022-11-22 16:00 UTC, llddang commented on llddang/java_racing_car/src/main/java/com/llddang/javaracingcar/Main.java
> +    gamePlay.printWinner();
중간 과정을 수행하지 않아 등록된 자동차 전부가 우승자로 뜹니다!
startCarRacing 안으로 printWinner를 넣겠습니다!

2024-12-17 09:58 UTC, closed without merging